import { Document, Page, Text, View } from "@react-pdf/renderer";

import type { ExportBundle } from "@/lib/exports/types";
import { formatDateRangeLabel } from "@/lib/exports/fetch-data";

import { pdfStyles as s } from "./styles";

export function ComparisonReportDocument({
  bundle,
  evaluation,
}: {
  bundle: ExportBundle;
  evaluation: string;
}) {
  const rangeLabel = formatDateRangeLabel(bundle.start_date, bundle.end_date);

  return (
    <Document>
      <Page size="A4" style={s.page}>
        <Text style={s.coverTitle}>BranchWise AI</Text>
        <Text style={s.coverSubtitle}>Branch Comparison</Text>
        <Text style={s.coverMeta}>{rangeLabel}</Text>
        <Text style={s.coverMeta}>Generated by: {bundle.generated_by}</Text>
        <Text style={s.footer}>BranchWise AI</Text>
      </Page>

      <Page size="A4" style={s.page}>
        <Text style={s.h1}>Side-by-side KPIs</Text>
        <View style={s.tableHeader}>
          <Text style={s.cellWide}>Metric</Text>
          {bundle.by_branch.map((b) => (
            <Text key={b.branch_id} style={s.cell}>
              {b.branch_name}
            </Text>
          ))}
        </View>
        {(
          [
            ["Revenue (€)", (b: (typeof bundle.by_branch)[number]) => String(b.total_revenue)],
            ["Occupancy %", (b: (typeof bundle.by_branch)[number]) => `${b.avg_occupancy}%`],
            ["Neg. feedback", (b: (typeof bundle.by_branch)[number]) => String(b.total_negative_feedback)],
            ["Reports", (b: (typeof bundle.by_branch)[number]) => String(b.reports_submitted)],
          ] as const
        ).map(([label, fn]) => (
          <View key={label} style={s.tableRow}>
            <Text style={s.cellWide}>{label}</Text>
            {bundle.by_branch.map((b) => (
              <Text key={b.branch_id} style={s.cell}>
                {fn(b)}
              </Text>
            ))}
          </View>
        ))}
        <Text style={s.h1}>AI evaluation</Text>
        {evaluation.split(/\n\n+/).map((p, i) => (
          <Text key={i} style={s.paragraph}>
            {p.trim()}
          </Text>
        ))}
        <Text style={s.footer}>BranchWise AI — Comparison</Text>
      </Page>
    </Document>
  );
}
