import { Document, Page, Text, View } from "@react-pdf/renderer";

import type { ExportBundle } from "@/lib/exports/types";
import { formatDateRangeLabel } from "@/lib/exports/fetch-data";

import { pdfStyles as s } from "./styles";

export type ManagementPdfProps = {
  bundle: ExportBundle;
  executiveSummary: string;
  highlights: string[];
  branchInsights: Record<string, string>;
};

export function ManagementReportDocument({ bundle, executiveSummary, highlights, branchInsights }: ManagementPdfProps) {
  const rangeLabel = formatDateRangeLabel(bundle.start_date, bundle.end_date);
  const generatedAt = new Intl.DateTimeFormat("en-GB", { dateStyle: "long", timeStyle: "short" }).format(new Date());

  return (
    <Document>
      <Page size="A4" style={s.page}>
        <Text style={s.coverTitle}>BranchWise AI</Text>
        <Text style={s.coverSubtitle}>Management Report</Text>
        <Text style={s.coverMeta}>Date range: {rangeLabel}</Text>
        <Text style={s.coverMeta}>Generated by: {bundle.generated_by}</Text>
        <Text style={s.coverMeta}>Generated on: {generatedAt}</Text>
        <View style={{ marginTop: 40, height: 60, backgroundColor: "#e5e7eb", justifyContent: "center", alignItems: "center" }}>
          <Text style={{ color: "#6b7280" }}>Company logo</Text>
        </View>
        <Text style={s.footer}>BranchWise AI — Confidential</Text>
      </Page>

      <Page size="A4" style={s.page}>
        <Text style={s.h1}>Executive Summary</Text>
        {executiveSummary.split(/\n\n+/).map((p, i) => (
          <Text key={i} style={s.paragraph}>
            {p.trim()}
          </Text>
        ))}
        <View style={s.box}>
          <Text style={s.h2}>Key highlights</Text>
          {highlights.map((h, i) => (
            <Text key={i} style={s.bullet}>
              • {h}
            </Text>
          ))}
        </View>
        <Text style={s.footer}>BranchWise AI — Management Report</Text>
      </Page>

      <Page size="A4" style={s.page}>
        <Text style={s.h1}>KPI Overview</Text>
        <View style={s.tableHeader}>
          <Text style={s.cell}>Branch</Text>
          <Text style={s.cell}>Revenue</Text>
          <Text style={s.cell}>Occupancy</Text>
          <Text style={s.cell}>Neg. FB</Text>
          <Text style={s.cell}>Issues</Text>
          <Text style={s.cell}>Reports</Text>
        </View>
        {bundle.by_branch.map((b) => (
          <View key={b.branch_id} style={s.tableRow}>
            <Text style={s.cell}>{b.branch_name}</Text>
            <Text style={s.cell}>€{b.total_revenue}</Text>
            <Text style={s.cell}>{b.avg_occupancy}%</Text>
            <Text style={s.cell}>{b.total_negative_feedback}</Text>
            <Text style={s.cell}>{b.repeated_issues}</Text>
            <Text style={s.cell}>{b.reports_submitted}</Text>
          </View>
        ))}
        <Text style={s.footer}>BranchWise AI — KPI Overview</Text>
      </Page>

      {bundle.by_branch.map((b) => {
        const branchReports = bundle.reports.filter((r) => r.branch_id === b.branch_id).slice(0, 8);
        return (
          <Page key={b.branch_id} size="A4" style={s.page}>
            <Text style={s.h1}>{b.branch_name}</Text>
            <Text style={s.paragraph}>
              Revenue €{b.total_revenue} · Occupancy {b.avg_occupancy}% · Negative feedback {b.total_negative_feedback} ·
              Reports {b.reports_submitted}
            </Text>
            <Text style={s.h2}>AI insight</Text>
            <Text style={s.paragraph}>{branchInsights[b.branch_id] ?? "—"}</Text>
            <Text style={s.h2}>Submitted reports</Text>
            {branchReports.length === 0 ? (
              <Text style={s.paragraph}>No reports in this period.</Text>
            ) : (
              branchReports.map((r) => (
                <Text key={r.id} style={s.bullet}>
                  • {r.template_title} ({r.period_start} – {r.period_end}): {r.data_summary}
                </Text>
              ))
            )}
            <Text style={s.footer}>BranchWise AI — {b.branch_name}</Text>
          </Page>
        );
      })}

      <Page size="A4" style={s.page}>
        <Text style={s.h1}>Appendix</Text>
        <Text style={s.paragraph}>
          This report aggregates operational KPIs, submitted branch reports, and AI-generated narrative summaries for the
          selected period. Figures reflect data stored in BranchWise AI at generation time.
        </Text>
        <Text style={s.paragraph}>Data period: {rangeLabel}</Text>
        <Text style={s.paragraph}>Generated by BranchWise AI on {generatedAt}.</Text>
        <Text style={s.footer}>BranchWise AI — Appendix</Text>
      </Page>
    </Document>
  );
}
