import { Document, Page, Text, View } from "@react-pdf/renderer";

import type { ExportBundle } from "@/lib/exports/types";
import { formatDateRangeLabel } from "@/lib/exports/fetch-data";

import { pdfStyles as s } from "./styles";

export function WeeklyPackageDocument({
  bundle,
  highlights,
  branchSummaries,
}: {
  bundle: ExportBundle;
  highlights: string;
  branchSummaries: Record<string, string>;
}) {
  const rangeLabel = formatDateRangeLabel(bundle.start_date, bundle.end_date);

  return (
    <Document>
      <Page size="A4" style={s.page}>
        <Text style={s.coverTitle}>BranchWise AI</Text>
        <Text style={s.coverSubtitle}>Weekly Performance Package</Text>
        <Text style={s.coverMeta}>{rangeLabel}</Text>
        <Text style={s.coverMeta}>Generated by: {bundle.generated_by}</Text>
        <Text style={s.footer}>BranchWise AI</Text>
      </Page>

      <Page size="A4" style={s.page}>
        <Text style={s.h1}>Weekly highlights</Text>
        {highlights.split(/\n\n+/).map((p, i) => (
          <Text key={i} style={s.paragraph}>
            {p.trim()}
          </Text>
        ))}
        <Text style={s.footer}>BranchWise AI — Weekly</Text>
      </Page>

      {bundle.by_branch.map((b) => {
        const branchReports = bundle.reports.filter((r) => r.branch_id === b.branch_id);
        return (
          <Page key={b.branch_id} size="A4" style={s.page}>
            <Text style={s.h1}>{b.branch_name}</Text>
            <Text style={s.h2}>AI summary</Text>
            <Text style={s.paragraph}>{branchSummaries[b.branch_id] ?? "—"}</Text>
            <Text style={s.h2}>Submissions ({branchReports.length})</Text>
            {branchReports.length === 0 ? (
              <Text style={s.paragraph}>No submissions this week.</Text>
            ) : (
              branchReports.map((r) => (
                <View key={r.id} style={{ marginBottom: 8 }}>
                  <Text style={{ fontSize: 10, fontWeight: "bold" }}>
                    {r.template_title} — {r.period_start} to {r.period_end}
                  </Text>
                  <Text style={s.paragraph}>{r.data_summary}</Text>
                </View>
              ))
            )}
            <Text style={s.footer}>BranchWise AI — {b.branch_name}</Text>
          </Page>
        );
      })}
    </Document>
  );
}
